Kegiatan/urls.py
from django.urls import path
from . import views

app_name = 'Kegiatan'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('/tambah-peserta', views.tambah_peserta, name='tambah-peserta')
]

main/urls.py
from django.urls import path
from . import views
from .views import MatkulView, MatkulDetail, MatkulDelete
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('games', views.games, name='games'),
    path('matkul', MatkulView.as_view(), name='matkul'),
    path('detail/<int:pk>/', MatkulDetail.as_view(), name='detail-matkul'),
    path('input-matkul', views.input_matkul, name='input-matkul'),
    path('detail/<int:pk>/remove', MatkulDelete.as_view(), name='remove-matkul'),
]

story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('Kegiatan', include('Kegiatan.urls')),
]

Kegiatan/models.py
from django.db import models

# Create your models here.
class Peserta(models.Model):
    pilihan = (
            ('DOTA2','Mabar DOTA 2'),
            ('ML', 'Mabar ML'),
            ('LOL', 'Mabar LOL')
    )
    nama = models.CharField(max_length=300)
    kegiatan = models.CharField(max_length=300, choices=pilihan)
    
    def __str__(self):
        return self.nama

main/models.py
from django.db import models

class Matkul(models.Model):
    matakuliah = models.CharField(max_length=300)
    dosen = models.CharField(max_length=300)
    sks = models.CharField(max_length=300)
    deskripsi = models.TextField()
    semester = models.CharField(max_length=300)
    kelas = models.CharField(max_length=300)

    def __str__(self):
        return self.matakuliah

Kegiatan/forms.py
from django import forms
from .models import Peserta

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'nama',
            'kegiatan'
        ]
        
        widgets = {
            'nama':forms.TextInput(attrs={'class':'form-control'}),
            'kegiatan':forms.ChoiceField(label="", initial='', widget=forms.Select(), required=True)
        }

main/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'matakuliah',
            'dosen',
            'sks',
            'deskripsi',
            'semester',
            'kelas'
        ]
        widgets = {
            'matakuliah':forms.TextInput(attrs={'class':'form-control','placeholder':'Masukkan Nama Matakuliah'}),
            'dosen':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Masukkan Nama Dosen'}),
            'sks':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Masukkan Jumlah SKS'}),
            'deskripsi':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Masukkan Deskripsi Matakuliah'}),
            'semester':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Masukkan Semester, Contoh: Gasal 2021/2020'}),
            'kelas':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Masukkan Ruang Kelas, Contoh: R2.4001'})
        }


Kegiatan/views.py
from django.shortcuts import render
from .forms import PesertaForm
from .models import Peserta
from django.views.generic import ListView, DetailView, DeleteView
from django.urls import reverse_lazy
# Create your views here.
def kegiatan(request):
    return render(request, 'main/kegiatan.html')

def tambah_peserta(request):
    form = PesertaForm(request.POST or None)
    if form.is_valid():
        form.save()

    context = {
        "form":form
    }
    return render(request, 'main/tambah-peserta.html', context)

main/views.py
from django.shortcuts import render
from .forms import MatkulForm
from .models import Matkul
from django.views.generic import ListView, DetailView, DeleteView
from django.urls import reverse_lazy

def home(request):
    return render(request, 'main/home.html')

def profile(request):
    return render(request, 'main/profile.html')

def games(request):
    return render(request, 'main/games.html')

def input_matkul(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()

    context = {
        "form":form
    }
    return render(request, 'main/input-matkul.html', context)

class MatkulView(ListView):
    model = Matkul
    template_name = "main/matkul.html"

class MatkulDetail(DetailView):
    model = Matkul
    template_name = "main/detail-matkul.html"

class MatkulDelete(DeleteView):
    model = Matkul
    template_name = "main/remove-matkul.html"
    success_url = reverse_lazy('main:matkul')

Kegiatan/templates/main/kegiatan.html
{% extends 'base.html' %}
{% block meta %}
    <title>Input Mata Kuliah</title>
{% endblock meta %}

    {% block content %}
    <a href="{% url 'Kegiatan:tambah-peserta' %}" class="btn btn-outline-dark btn-lg text-light">Tambah Peserta</a>
    <div class="container text-xl-center text-lg-center text-md-center text-sm-center big-wrapper">
        <div class="row d-flex justify-content-center">
            <div class="card m-2" style="width: 20rem">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-dark">Mabar DOTA 2</h5>
                </div>
            </div>
            <div class="card m-2" style="width: 20rem">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-dark">Mabar Mobile Legend</h5>
                </div>
            </div>
        </div>
        </div>
    {% endblock %}

Kegiatan/templates/main/tambah-peserta.html
{% extends 'base.html' %}
{% block meta %}
    <title>Tambah Peserta</title>
{% endblock meta %}

    {% block content %}
        <div class="container big-wrapper text-dark">
            <div class="form-group">
                <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value='Tambah' class="btn btn-outline-light btn-lg text-light btn-block matkuladd-button">
                </form>
            </div>
            <div class="container text-xl-center text-lg-center text-md-center text-sm-center big-wrapper">
            <div class="row d-flex justify-content-center">
                {% for peserta in PesertaForm %}
                <div class="card m-2" style="width: 20rem">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title text-dark">{{ peserta.nama }}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    {% endblock %}

main/templates/main/detail-matkul.html
{% extends 'base.html' %}
{% block meta %}
<title>Mata Kuliah</title>
{% endblock meta %}
    {% block content %}
        <div class="container big-wrapper">
        <h1 class="text-light mb-5" style="text-align: center; color: #ffffff !important;">{{ matkul.matakuliah }}</h1>
        <ul style="color: white;">
            <li>Dosen : {{ matkul.dosen }}</li>
            <li>Jumlah SkS : {{ matkul.sks }} SKS</li>
            <li>Deskripsi : {{ matkul.deskripsi }}</li>
            <li>semester : {{ matkul.semester }}</li>
            <li>Ruang : {{ matkul.kelas }}</li>
        </ul>
        </div>
    {% endblock %}

main/templates/main/games.html
{% extends 'base.html' %}
{% load static%}

    {% block meta %}
    <title>Completed Games</title>
    {% endblock meta %}
      
{% block content %}
    <div class="about-me">
        <p1>
            Hello, I'm Aflah just an Enthusiastic Gamer. This is my list of the game I've been completed <br>
            - The Witcher 3: Wild Hunt <br>
            - Star Wars Jedi: Fallen Order <br>
            - The Elder Scrolls V: Skyrim <br>
            - Tomb Raider (2013) <br>
            - Far Cry 3 <br>
            - Far Cry 4 <br>
            - Grand Theft Auto V <br>
            - Sleeping Dogs <br>
            - Call of Duty 4: Modern Warfare 1, 2, 3 <br>
            - Assassin's Creed Black Flag, Rogue, Origins, Odyssey <br>
            - Pokemon Ruby, Emerald, Sapphire, Leaf Green, X, Ultra Sun, Omega Ruby <br>
        </p1>
    </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static%}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}
        <div class="wrapper">
            <header>
                <div class="content">
                    <h1>Welcome <br>
                    to my website</h1>
                    <p class="i">I am : <br>
                    Enthusiastic Gamer <br>
                    Black Belt Tae Kwon Do <br>
                    Student at University of Indonesia</p>
                </div>  
                    <img src= "{% static 'img/Social Media.png' %}" alt="" class="social-media">
            </header>
        </div>
    {% endblock content %}

main/templates/main/input-matkul.html
{% extends 'base.html' %}
{% block meta %}
    <title>Input Mata Kuliah</title>
{% endblock meta %}

    {% block content %}
        <div class="container big-wrapper text-dark">
            <div class="form-group">
                <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value='Save' class="btn btn-outline-light btn-lg text-light btn-block matkuladd-button">
                </form>
            </div>
        </div>
    {% endblock %}

main/templates/main/matkul.html
{% extends 'base.html' %}

{% block meta %}
<title>Mata Kuliah</title>
{% endblock meta %}
{% block content %}
    <div class="container text-xl-center text-lg-center text-md-center text-sm-center big-wrapper">
        <div class="row d-flex justify-content-left">
        {% for matkul in object_list %}
        <div class="card m-2" style="width: 20rem">
            <div class="card-body d-flex flex-column">
                <h5 class="card-title text-dark">
                    {{ matkul.matakuliah }}
                </h5>
                <p class="card-text text-dark">
                    {{ matkul.deskripsi }}
                </p>
                <p class="card-text text-dark">
                    {{ matkul.kelas }}
                </p>
                <div class="mt-auto">
                <a href="{% url 'main:detail-matkul' matkul.pk %}" class="btn btn-outline-dark btn-lg text-dark btn-block matkul-buttons">Details</a>
                <a href="{% url 'main:remove-matkul' matkul.pk %}" class="btn btn-outline-dark btn-lg text-dark btn-block matkul-buttons">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/main/profile.html
{% extends 'base.html' %}
{% load static%}
    {% block meta %}
    <title>Profile</title>
    {% endblock meta %} 
  {% block content %}
        <div class="wrapper">
            <header>
                <div class="identitas">
                    <p>
                        Nama         : Aflah Alifu Na Mappatajang Rahman<br>
                        NPM          : 1906353675<br>
                        Angkatan     : 2019<br>
                        Hobi         : Taekwondo, Main game<br>
                        Deskripsi    : Agak Introvert, Senang Olahraga, Percaya Diri<br>
                        Sekolah      : Universitas Indonesia<br>
                    </p>
                </div>
                    <img src= "{% static 'img/Social Media.png' %}" alt="" class="social-media">
                    <img src= "{% static 'img/foto.png' %}" alt="" class="foto">
                    <img src= "{% static 'img/Riwayat Pendidikan.png' %}" alt="" class="riwayat">
            </header>
        </div>
{% endblock content %}

main/templates/main/remove-matkul.html
{% extends 'base.html' %}

    {% block content %}
        <div class="container text-xl-center text-lg-center text-md-center text-sm-center big-wrapper text-light">
            <h1 style="text-align: center; color: #ffffff !important;" class="mb-5">{{ matkul.matakuliah }}</h1>
            <div class="form-group mb-5">
                <form method="POST">
                    {% csrf_token %}
                    <strong>Delete {{ matkul.matakuliah }}, are you sure?</strong><br/>
            </div>
            <button class="btn btn-danger btn-block delete">Delete</button>
        </div>
    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
        <a class="navbar-brand" href="#">Z</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'main:home' %}">Home<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'main:profile' %}">Profile</a>
            <a class="nav-link" href="{% url 'main:games' %}">Completed Games</a>
            <a class="nav-link" href="{% url 'main:matkul' %}">Mata Kuliah</a>
            <a class="nav-link" href="{% url 'main:input-matkul' %}">Input Mata Kuliah</a>
            <a class="nav-link" href="{% url 'Kegiatan:kegiatan' %}">Kegiatan</a>
          </div>
        </div>
      </nav>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
{% block content %}
{% endblock content %}
</html>